### ISSUE TITLE
Transition styles are not replaced

### ISSUE THREAD

**Issue by abishekrsrikaanth** [clickfwd/css-prefixer-tailwindui#1]
@jreviews, thanks for this wonderful tool you have created. Its been quite useful. The one issue that I noticed is that it doesn't seem to work on transition tags

**Comment by jreviews** [comment]
@abishekrsrikaanth Thanks. Do you mean Alpine JS transition attributes?

**Comment by abishekrsrikaanth** [comment]
Correct
